// katalog.js – DIE zentrale Liste aller Übungen.
// Neue Übung = HTML-Datei in diesen Ordner legen + hier einen Eintrag ergänzen.
// id: eindeutig, nur Kleinbuchstaben, Ziffern und Bindestriche (wird in der Datenbank benutzt)
// offen: Standard, ob die Übung ohne Code spielbar ist (in der Konsole umschaltbar)

// quelle: { werk, lektion } – nur für dich: erscheint ausschließlich in der Konsole, nie in der Zentrale.
// Trainings (JSON-Pakete): datei 'training.html?set=<Dateiname ohne .json>', id = "id" in der JSON-Datei, teile = Anzahl Teile

export const KATALOG = [
  {
    id: 'neue-wege-im-beruf',
    titel: 'Neue Wege im Beruf',
    untertitel: 'Pendeln oder umziehen · Wortstellung · Agentur für Arbeit · Anerkennung · Anfragen schreiben',
    datei: 'training.html?set=neue-wege-im-beruf',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#0f6aa6',
    dauer: '6 Teile',
    teile: 6,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 1 }
  },
  {
    id: 'der-weg-zum-job',
    titel: 'Der Weg zum Job',
    untertitel: 'Berufe · zweiteilige Konnektoren · Lebenslauf · Ausbildungswege · Bewerbung · Termine',
    datei: 'training.html?set=der-weg-zum-job',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#13836b',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 2 }
  },
  {
    id: 'ankommen-im-betrieb',
    titel: 'Ankommen im Betrieb',
    untertitel: 'Abteilungen · erster Arbeitstag · Vergleiche · Regeln · Small Talk · das Wort „es“ · Mails und Aufträge',
    datei: 'training.html?set=ankommen-im-betrieb',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#c2611f',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 3 }
  },
  {
    id: 'zusammenarbeit-im-team',
    titel: "Zusammenarbeit im Team",
    untertitel: "Besprechungen · Relativsätze mit wer · Konflikte lösen · Übergaben · Nomen-Verb-Verbindungen · Protokolle",
    datei: 'training.html?set=zusammenarbeit-im-team',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#5b5fa8',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 4 }
  },
  {
    id: 'das-unternehmen-praesentieren',
    titel: "Das Unternehmen präsentieren",
    untertitel: "Firmenporträt · Passiv und Ersatzformen · Messestand · Indefinitpronomen · Kundenanfragen · Präsentationen",
    datei: 'training.html?set=das-unternehmen-praesentieren',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#8a5a2b',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 5 }
  },
  {
    id: 'gutes-klima-im-team',
    titel: "Gutes Klima im Team",
    untertitel: "Teamfähigkeit · als, als ob, als wenn · Telefonieren · Passiv mit sein · Hotel und Service · Defekte melden · Online-Konferenzen",
    datei: 'training.html?set=gutes-klima-im-team',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#2f7d5c',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 6 }
  },
  {
    id: 'der-kunde-im-mittelpunkt',
    titel: "Der Kunde im Mittelpunkt",
    untertitel: "Kundenkontakt · Mails an Kunden · Textzusammenhang · Angebote · Bestellungen · dadurch, dass und indem · Reklamationen · Entscheidungen",
    datei: 'training.html?set=der-kunde-im-mittelpunkt',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#b0413e',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 7 }
  },
  {
    id: 'sicher-und-gut-informiert',
    titel: "Sicher und gut informiert",
    untertitel: "Schilder und Warnzeichen · Elternzeit und Elterngeld · Wörter mit Präposition · Geräte erklären · indirekte Rede · Dienstpläne · Arbeitsrecht",
    datei: 'training.html?set=sicher-und-gut-informiert',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#3b6ea5',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 8 }
  },
  {
    id: 'gesund-und-zufrieden-im-job',
    titel: "Gesund und zufrieden im Job",
    untertitel: "Gefühle im Beruf · Gesundheitsförderung · Nominalisierung · gutes Arbeitsumfeld · Modalpartikeln · Mitarbeitergespräch · Kündigung · Kritik",
    datei: 'training.html?set=gesund-und-zufrieden-im-job',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#6b8e23',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 9 }
  },
  {
    id: 'arbeitswelt-von-morgen',
    titel: "Arbeitswelt von morgen",
    untertitel: "Digitalisierung · Roboter · Partizipien als Adjektive · Selbstständigkeit · Bescheid und Widerspruch · während und Präpositionen mit Genitiv · Weiterbildung",
    datei: 'training.html?set=arbeitswelt-von-morgen',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#2a6f97',
    dauer: '8 Teile',
    teile: 8,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Aspekte Beruf', lektion: 10 }
  },
  {
    id: 'umzug-ins-neue-buero',
    titel: "Umzug ins neue Büro",
    untertitel: "Arbeitsräume und Geräte · Bürosuche · etwas machen lassen · Umzugsfirma · Wann-warum-wie-wo · Mängel melden",
    datei: 'training.html?set=umzug-ins-neue-buero',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#5a8f5c',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 1 }
  },
  {
    id: 'rund-um-die-uhr-geoeffnet',
    titel: "Rund um die Uhr geöffnet",
    untertitel: "Kleine Läden und Arbeitszeiten · Verneinung mit nicht · Selbstständigkeit · Negationswörter · Dienstplan · Arbeitsaufträge",
    datei: 'training.html?set=rund-um-die-uhr-geoeffnet',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#c0562e',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 2 }
  },
  {
    id: 'meine-rechte-im-job',
    titel: "Meine Rechte im Job",
    untertitel: "Arbeit und Familie · Interessen vertreten · Benachteiligung · Abmahnung und Kündigung · Teilzeit · Beschwerden beantworten",
    datei: 'training.html?set=meine-rechte-im-job',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#c4554d',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 'Haltestelle A' }
  },
  {
    id: 'neu-im-team',
    titel: "Neu im Team",
    untertitel: "Tipps für den Start · Passiv Präteritum · sich vorstellen · Protokolle · Teamgespräche · Teamrollen",
    datei: 'training.html?set=neu-im-team',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#3f7f6a',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 3 }
  },
  {
    id: 'arbeiten-wo-andere-urlaub-machen',
    titel: "Arbeiten, wo andere Urlaub machen",
    untertitel: "Reiseformen · Angebote und Anfragen · Konjunktiv II der Vergangenheit · Berufe im Tourismus · Bewerbung · Gründe und Folgen",
    datei: 'training.html?set=arbeiten-wo-andere-urlaub-machen',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#1f86a8',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 4 }
  },
  {
    id: 'arbeitsformen-und-logistik',
    titel: "Arbeitsformen und Logistik",
    untertitel: "Vollzeit, Minijob, Zeitarbeit · Lohn und Vertrag · logistische Ketten · Probleme am Telefon lösen · Arbeitsbedingungen verhandeln · Telefonnotizen",
    datei: 'training.html?set=arbeitsformen-und-logistik',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#b5562f',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 'Haltestelle B' }
  },
  {
    id: 'handwerk-hat-zukunft',
    titel: "Handwerk hat Zukunft",
    untertitel: "Handwerksberufe und Werkzeuge · Vorgangspassiv · Zustandspassiv · Abläufe beschreiben · Verbesserungsvorschläge · trennbare und untrennbare Verben",
    datei: 'training.html?set=handwerk-hat-zukunft',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#8a6d1f',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 5 }
  },
  {
    id: 'neu-in-der-region',
    titel: "Neu in der Region",
    untertitel: "Wohnort und Arbeitsplatz · Vermutungen · Reportage · Nomen-Verb-Verbindungen · Bewerbung fürs duale Studium · Arbeitsvertrag · Ausflüge",
    datei: 'training.html?set=neu-in-der-region',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#4b7d3a',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 6 }
  },
  {
    id: 'gesund-bleiben-im-beruf',
    titel: "Gesund bleiben im Beruf",
    untertitel: "Gesundheitsangebote · Meinungen und Abwägen · Infinitiv mit zu · Arbeitstag in der Pflege · Probleme melden · Pflegebericht · einfacher leben",
    datei: 'training.html?set=gesund-bleiben-im-beruf',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#2f8f83',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 7 }
  },
  {
    id: 'kueche-service-lieferung',
    titel: "Küche, Service, Lieferung",
    untertitel: "Restaurantangebote · Adjektivdeklination · Küchengeräte · damit, um … zu, zum · Kompetenzen in der Küche · Lieferungen reklamieren · erfolgreich verhandeln",
    datei: 'training.html?set=kueche-service-lieferung',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#b24a2b',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 8 }
  },
  {
    id: 'bewerbung-schritt-fuer-schritt',
    titel: "Bewerbung Schritt für Schritt",
    untertitel: "Berufswortschatz · Jobsuche online · Jobbörsen und Jobmessen · Schlüsselqualifikationen · Anschreiben · Bewerbungsgespräch · Beschwerden beantworten",
    datei: 'training.html?set=bewerbung-schritt-fuer-schritt',
    typ: 'Training',
    niveau: 'B1/B2',
    themen: ['Prüfungsvorbereitung', 'Beruf'],
    farbe: '#c4554d',
    dauer: '7 Teile',
    teile: 7,
    reihe: 'Prüfungstraining B1/B2',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 'Haltestelle C' }
  },
  {
    id: "weltweit-im-netz",
    titel: "Weltweit im Netz",
    untertitel: "Internationaler Handel · kultursensible Webseiten · indem, ohne zu, ohne dass · Beschwerdebrief · Partizipien als Adjektive · …einander · Unternehmensporträt",
    datei: "training.html?set=weltweit-im-netz",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#2f6f9f",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 9 }
  },
  {
    id: 'handel-kontor',
    titel: 'Das Handelskontor',
    untertitel: 'Wortschatz Handel · indem, damit, um … zu, ohne dass, statt dass',
    datei: 'handel-kontor.html',
    typ: 'Spiel',
    niveau: 'B1/B2',
    themen: ['Handel', 'Konnektoren', 'Beruf'],
    farbe: '#1f6f78',
    dauer: '20 Min.',
    aufgaben: 36,
    reihe: 'Spiele',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 9 }
  },
  {
    id: 'partizip-presse',
    titel: 'Die Satzpresse',
    untertitel: 'Partizip I und II als Adjektiv – statt Relativsatz',
    datei: 'partizip-presse.html',
    typ: 'Spiel',
    niveau: 'B1/B2',
    themen: ['Grammatik', 'Partizipien', 'Relativsätze'],
    farbe: '#7a3b69',
    dauer: '20 Min.',
    aufgaben: 30,
    reihe: 'Spiele',
    offen: true,
    quelle: { werk: 'Linie 1 Beruf', lektion: 9 }
  },
  {
    id: "gut-geregelt-im-job",
    titel: "Gut geregelt im Job",
    untertitel: "Arbeitsvertrag · Vertragssprache · Regeln im Betrieb · Präpositionen mit Genitiv · Gespräche mit Vorgesetzten · Kündigung · Arbeitsschutz",
    datei: "training.html?set=gut-geregelt-im-job",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#4f7d4a",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 10 }
  },
  {
    id: "digital-im-job",
    titel: "Digital im Job",
    untertitel: "Medien im Alltag · je … desto/umso · Grafiken beschreiben · Reklamation · Nomen-Verb-Verbindungen · Jobsuche mit Social Media",
    datei: "training.html?set=digital-im-job",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#3a6ea5",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 11 }
  },
  {
    id: "ankommen-in-der-welt",
    titel: "Ankommen in der Welt",
    untertitel: "Globalisierung · Willkommensbrief · Folgen ausdrücken · Arbeitsalltag in Deutschland · Kommunikation im Betrieb · Präpositionen · Fernbeziehungen",
    datei: "training.html?set=ankommen-in-der-welt",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#2e7d6b",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 12 }
  },
  {
    id: "technik-und-datenschutz",
    titel: "Technik und Datenschutz",
    untertitel: "Produkte beschreiben · Computerprobleme melden · eine Schulung planen · Datenschutz (DSGVO) · erklären, wie etwas funktioniert",
    datei: "training.html?set=technik-und-datenschutz",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#c0624f",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: "Haltestelle D" }
  },
  {
    id: "konflikte-loesen",
    titel: "Konflikte fair lösen",
    untertitel: "Streit im Arbeitsalltag · Lösungen finden · berufliche Telefongespräche · irreale Bedingungen in der Vergangenheit · Bestätigungsmail · Relativsätze im Genitiv",
    datei: "training.html?set=konflikte-loesen",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#8a5a2b",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 13 }
  },
  {
    id: "man-lernt-nie-aus",
    titel: "Man lernt nie aus",
    untertitel: "Lernbiografien · Eigenschaften · Konjunktiv I · Förderprogramme · Anfrage an ein Weiterbildungsinstitut · Lernen und Emotionen · als ob",
    datei: "training.html?set=man-lernt-nie-aus",
    typ: "Training",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Beruf"],
    farbe: "#5b6bb0",
    dauer: "7 Teile",
    teile: 7,
    reihe: "Prüfungstraining B1/B2",
    offen: true,
    quelle: { werk: "Linie 1 Beruf", lektion: 14 }
  },
  {
    id: "problem-loesen",
    titel: "Gemeinsam ein Problem lösen",
    untertitel: "Prüfungssimulation Sprechen · 27 Situationen am Arbeitsplatz · Zeitanzeige · Selbstcheck · Redemittel-Training",
    datei: "problem-loesen.html",
    typ: "Simulation",
    niveau: "B1/B2",
    themen: ["Prüfungsvorbereitung", "Sprechen", "Beruf"],
    farbe: "#2f6b5e",
    dauer: "je 4 Min.",
    reihe: "Mündliche Prüfung",
    offen: true
  },
  {
    id: "smalltalk",
    titel: "Smalltalk-Profi",
    untertitel: "Smalltalk bei der Arbeit: Themen, Begriffe, Reaktionen, Du oder Sie · allein mit Zeitdruck oder live mit der Klasse",
    datei: "smalltalk.html",
    typ: "Spiel",
    niveau: "B1/B2",
    themen: ["Sprechen", "Beruf", "Kommunikation"],
    farbe: "#b5562f",
    dauer: "10 Min.",
    reihe: "Mündliche Prüfung",
    offen: true
  }
];

export const exById = id => KATALOG.find(e => e.id === id);
