// smalltalk-daten.js – Fragen für „Smalltalk-Profi“ (Einzelspiel und Live-Runde)
// l = Index der richtigen Antwort (wird im Spiel gemischt), e = kurze Erklärung nach der Auflösung
export const KATEGORIEN = {
  thema: '💬 Themen', start: '👋 Einstieg', reag: '🙂 Reagieren', wort: '📖 Begriffe', du: '🤝 Du oder Sie', ende: '🚪 Gespräch beenden', kultur: '🌍 Gute Sitten'
};

export const FRAGEN = [
  // Themen
  { k: 'thema', q: 'Welches Thema passt am besten für Smalltalk mit einer neuen Kollegin?', opts: ['das Wetter oder das Wochenende', 'ihr Gehalt und ihre Miete', 'ihre Religion und ihr Glaube', 'ihre letzte Krankheit'], l: 0, e: 'Wetter, Wochenende, Urlaub, Essen und Hobbys sind sichere Themen. Geld, Religion, Politik und Krankheiten sind tabu.' },
  { k: 'thema', q: 'Welches Thema ist für Smalltalk in der Kaffeeküche eher ungeeignet?', opts: ['Für welche Partei wählst du?', 'Wie war dein Urlaub?', 'Hast du das Spiel gestern gesehen?', 'Kennst du ein gutes Restaurant hier?'], l: 0, e: 'Politische Fragen können schnell zu Streit führen – im Smalltalk lieber vermeiden.' },
  { k: 'thema', q: 'Ein Kollege fragt: „Was verdienst du eigentlich?“ – Wie ist das in Deutschland?', opts: ['Das gilt als sehr unhöflich.', 'Das ist eine normale Frage.', 'Das fragt man nur am ersten Tag.', 'Das fragt man nur die Chefin.'], l: 0, e: 'Über das eigene Gehalt spricht man in Deutschland im Smalltalk normalerweise nicht.' },
  { k: 'thema', q: 'Was ist ein „sicheres“ Smalltalk-Thema?', opts: ['Pläne für den Feierabend', 'Probleme in der Ehe', 'Schulden und Kredite', 'der Streit mit dem Chef'], l: 0, e: 'Leichte, positive Themen funktionieren am besten. Private Probleme gehören nicht in den Smalltalk.' },
  { k: 'thema', q: 'Worüber spricht man beim Smalltalk eher NICHT?', opts: ['über das Gewicht einer Kollegin', 'über einen neuen Kinofilm', 'über das Essen in der Kantine', 'über Pläne für den Urlaub'], l: 0, e: 'Kommentare über Aussehen oder Körper sind verletzend und tabu.' },
  { k: 'thema', q: 'Am Montagmorgen ist die typische Smalltalk-Frage …', opts: ['„Wie war dein Wochenende?“', '„Wie viel Miete zahlst du?“', '„Warum bist du nicht verheiratet?“', '„Glaubst du an Gott?“'], l: 0, e: 'Montags fragt man nach dem Wochenende, freitags nach den Plänen fürs Wochenende.' },
  // Einstieg
  { k: 'start', q: 'Sie stehen am Kopierer neben einer Kollegin aus einer anderen Abteilung. Wie beginnen Sie ein Gespräch?', opts: ['„Ganz schön voll heute hier, oder?“', '„Wer sind Sie denn eigentlich?“', '„Sie brauchen aber wirklich lange!“', 'Sie warten und sagen gar nichts.'], l: 0, e: 'Eine kleine Beobachtung zur Situation ist ein guter, lockerer Einstieg.' },
  { k: 'start', q: 'Wie beginnt man Smalltalk mit einer offenen Frage?', opts: ['„Was machst du am liebsten in der Freizeit?“', '„Trinkst du deinen Kaffee mit Milch?“', '„Bist du neu hier in der Abteilung?“', '„Ist das hier dein fester Platz?“'], l: 0, e: 'Offene Fragen (W-Fragen) bringen das Gespräch in Gang – Ja/Nein-Fragen beenden es oft schnell.' },
  { k: 'start', q: 'Neuer Kollege am ersten Tag in der Kantine. Was passt?', opts: ['„Hallo, ich bin Sara aus der Buchhaltung. Du bist neu hier, oder?“', '„Tut mir leid, der Platz ist für eine Kollegin reserviert.“', '„Hallo! Was hast du für ein Auto, und was hat es gekostet?“', '„In unserer Abteilung arbeiten nur richtig gute Leute.“'], l: 0, e: 'Sich vorstellen und eine einfache Frage stellen – so fühlen sich Neue willkommen.' },
  { k: 'start', q: 'Im Aufzug mit der Abteilungsleiterin. Was ist ein passender Satz?', opts: ['„Guten Morgen! Endlich mal Sonne heute.“', '„Ich brauche mehr Geld.“', '„Wohin fahren Sie im Urlaub? Mit wem?“', '„Ihr Büro ist viel größer als meins.“'], l: 0, e: 'Kurz, freundlich, unverbindlich – das Wetter ist der Klassiker.' },
  { k: 'start', q: 'Was bedeutet die Frage „Na, alles klar?“ im Büroflur?', opts: ['eine lockere Begrüßung', 'eine echte Frage nach Problemen', 'eine Kritik an der Arbeit', 'eine Einladung zum Essen'], l: 0, e: 'Man antwortet kurz: „Ja, danke, und bei dir?“ – keine lange Erklärung nötig.' },
  { k: 'start', q: 'Was antworten Sie am besten auf „Wie geht\'s?“ im Flur?', opts: ['„Gut, danke! Und dir?“', 'Eine lange Liste mit allen Problemen.', '„Warum fragst du?“', '„Das geht dich nichts an.“'], l: 0, e: '„Wie geht\'s?“ ist hier eine Begrüßung. Eine kurze positive Antwort mit Gegenfrage passt.' },
  // Reagieren
  { k: 'reag', q: 'Kollegin: „Ich war am Wochenende an der Ostsee.“ – Welche Reaktion hält das Gespräch am Laufen?', opts: ['„Oh, schön! Wo genau warst du denn?“', '„Aha. Na ja, wenn man Zeit hat …“', '„Ich mag das Meer eigentlich gar nicht.“', '„Schön für dich. Ich muss jetzt arbeiten.“'], l: 0, e: 'Interesse zeigen und eine Nachfrage stellen – so wird aus einem Satz ein Gespräch.' },
  { k: 'reag', q: 'Kollege: „Mein Sohn hat gestern sein erstes Fußballspiel gewonnen!“ – Was passt?', opts: ['„Glückwunsch! Spielt er schon lange?“', '„Fußball finde ich ehrlich gesagt langweilig.“', '„Mein Sohn spielt auch, er ist viel besser.“', '„Okay. Hast du die Mail von gestern gelesen?“'], l: 0, e: 'Sich mitfreuen und nachfragen – nicht das Gespräch auf sich selbst lenken.' },
  { k: 'reag', q: 'Kollegin: „Ich bin heute total müde.“ – Was ist eine freundliche Reaktion?', opts: ['„Oh je, hast du schlecht geschlafen?“', '„Ja, das sieht man dir heute an.“', '„Dann geh doch einfach nach Hause.“', '„Komisch, ich bin eigentlich nie müde.“'], l: 0, e: 'Mitgefühl zeigen, aber nicht zu persönlich werden.' },
  { k: 'reag', q: 'Was ist „aktives Zuhören“ im Smalltalk?', opts: ['nicken, nachfragen, kurz wiederholen', 'nur von sich selbst erzählen', 'aufs Handy schauen', 'das Thema schnell wechseln'], l: 0, e: '„Ach, wirklich?“, „Und dann?“, „Das klingt spannend!“ zeigen: Ich höre zu.' },
  { k: 'reag', q: 'Jemand erzählt von einem Hobby, das Sie nicht interessiert. Was tun Sie?', opts: ['höflich nachfragen und dann sanft das Thema wechseln', 'ehrlich sagen: „Das interessiert mich nicht.“', 'ohne ein Wort einfach weggehen', 'aufs Handy schauen, bis die Person aufhört'], l: 0, e: 'Höflich bleiben: kurze Nachfrage, dann z. B. „Apropos …“ und ein neues Thema.' },
  { k: 'reag', q: 'Mit welchem Wort wechselt man elegant das Thema?', opts: ['„Apropos …“', '„Trotzdem …“', '„Deshalb …“', '„Obwohl …“'], l: 0, e: '„Apropos Urlaub – fährst du dieses Jahr wieder nach Spanien?“' },
  // Begriffe
  { k: 'wort', q: 'Was bedeutet „Mahlzeit!“ im Büro um 12 Uhr?', opts: ['ein Gruß in der Mittagszeit', 'Ich habe Hunger.', 'Das Essen ist fertig.', 'eine Einladung zum Kochen'], l: 0, e: 'In vielen Betrieben grüßt man sich mittags mit „Mahlzeit!“ – man antwortet ebenfalls „Mahlzeit!“.' },
  { k: 'wort', q: 'Was ist ein „Einstand“?', opts: ['Neue Kollegen bringen etwas zu essen oder zu trinken mit.', 'das erste Gehalt, das man in einer Firma bekommt', 'der feste Parkplatz direkt am Eingang', 'eine kleine Prüfung am ersten Arbeitstag'], l: 0, e: 'Mit dem Einstand stellt man sich dem Team vor – z. B. mit Kuchen oder Brezeln.' },
  { k: 'wort', q: 'Und was ist ein „Ausstand“?', opts: ['eine kleine Feier, wenn jemand die Firma verlässt', 'ein kurzer Streik der Mitarbeitenden', 'Geld, das man Kollegen noch schuldet', 'eine Pause draußen vor dem Gebäude'], l: 0, e: 'Wer geht, gibt einen Ausstand – oft mit Sekt, Snacks oder einer Rede.' },
  { k: 'wort', q: 'Was ist ein „Brückentag“?', opts: ['ein Arbeitstag zwischen Feiertag und Wochenende', 'ein Arbeitstag auf einer großen Baustelle', 'ein Betriebsausflug in eine andere Stadt', 'der letzte Arbeitstag vor dem Urlaub'], l: 0, e: 'Viele nehmen am Brückentag Urlaub – beliebtes Smalltalk-Thema: „Machst du Brückentag?“' },
  { k: 'wort', q: 'Was ist „Flurfunk“?', opts: ['Gerüchte und Neuigkeiten, die im Betrieb erzählt werden', 'das Radio, das in der Kaffeeküche läuft', 'die neue Telefonanlage im ganzen Haus', 'Durchsagen über den Lautsprecher im Flur'], l: 0, e: 'Beim Flurfunk vorsichtig sein: Gerüchte weitererzählen kann schaden.' },
  { k: 'wort', q: '„Über jemanden lästern“ bedeutet …', opts: ['schlecht über eine Person sprechen, die nicht da ist', 'eine Person vor allen anderen laut loben', 'einer Kollegin bei schwerer Arbeit helfen', 'jemanden spontan zum Mittagessen einladen'], l: 0, e: 'Lästern gehört nicht zum guten Smalltalk – man spricht besser über Themen als über Personen.' },
  { k: 'wort', q: 'Was bedeutet „Ich geb\' einen aus“?', opts: ['Ich bezahle für die anderen.', 'Ich gehe raus.', 'Ich gebe etwas zurück.', 'Ich mache eine Pause.'], l: 0, e: 'Z. B. zum Geburtstag: „Heute geb\' ich einen aus – Kuchen für alle!“' },
  { k: 'wort', q: 'Ein „Schwätzchen halten“ heißt …', opts: ['kurz und locker plaudern', 'eine Rede halten', 'sich streiten', 'ein Protokoll schreiben'], l: 0, e: 'Plaudern, ein Schwätzchen halten, quatschen – alles Wörter für lockeres Reden.' },
  { k: 'wort', q: 'Was sagt man am Ende des Arbeitstages zu Kollegen?', opts: ['„Schönen Feierabend!“', '„Mahlzeit!“', '„Gute Besserung!“', '„Herzlichen Glückwunsch!“'], l: 0, e: 'Freitags auch: „Schönes Wochenende!“' },
  { k: 'wort', q: 'Ein Kollege ist erkältet. Was sagen Sie?', opts: ['„Gute Besserung!“', '„Viel Erfolg!“', '„Prost!“', '„Mahlzeit!“'], l: 0, e: 'Gute Besserung wünscht man Kranken. Beim Niesen sagt man oft „Gesundheit!“.' },
  { k: 'wort', q: 'Was ist ein „Betriebsausflug“?', opts: ['ein gemeinsamer Ausflug aller Mitarbeitenden', 'eine Dienstreise, die man allein macht', 'der Umzug der Firma in ein neues Haus', 'eine längere Fortbildung im Ausland'], l: 0, e: 'Danach gibt es viel Smalltalk-Stoff: „Wie fandest du den Ausflug?“' },
  // Du oder Sie
  { k: 'du', q: 'Wer bietet in Deutschland normalerweise das „Du“ an?', opts: ['die ältere oder ranghöhere Person', 'immer die jüngere Person', 'immer der Mann', 'der neue Kollege am ersten Tag'], l: 0, e: 'Das Du bietet meist die Person an, die älter ist oder eine höhere Position hat.' },
  { k: 'du', q: 'Wie bietet man höflich das Du an?', opts: ['„Wollen wir uns duzen? Ich bin Markus.“', '„Ab jetzt sagst du Du zu mir, klar?“', '„Sie sind mir viel zu förmlich, Frau Berg.“', '„Ich sieze grundsätzlich niemanden.“'], l: 0, e: 'Man fragt freundlich und nennt den eigenen Vornamen.' },
  { k: 'du', q: 'Sie wissen nicht, ob Sie eine Kollegin duzen oder siezen sollen. Was ist sicherer?', opts: ['erst einmal siezen', 'sofort duzen', 'gar nicht ansprechen', 'nur mit dem Nachnamen rufen'], l: 0, e: 'Im Zweifel siezt man – oder man achtet darauf, wie die anderen im Team sprechen.' },
  { k: 'du', q: 'In vielen Start-ups und Handwerksbetrieben …', opts: ['duzen sich oft alle.', 'muss man immer „Herr Doktor“ sagen.', 'darf man nicht miteinander sprechen.', 'gibt es keinen Smalltalk.'], l: 0, e: 'Die Unternehmenskultur ist verschieden – in Banken und Behörden siezt man häufiger.' },
  // Gespräch beenden
  { k: 'ende', q: 'Wie beenden Sie höflich ein Gespräch in der Kaffeeküche?', opts: ['„Ich muss dann mal wieder an den Schreibtisch. Bis später!“', '„Sorry, aber du redest wirklich viel zu viel.“', 'Sie drehen sich um und gehen ohne ein Wort.', '„Das ist mir jetzt ehrlich gesagt zu langweilig.“'], l: 0, e: 'Ein kurzer Grund und ein freundlicher Gruß – so endet Smalltalk positiv.' },
  { k: 'ende', q: 'Welcher Satz beendet ein Telefonat mit Smalltalk freundlich?', opts: ['„Schön, dass wir gesprochen haben. Einen schönen Tag noch!“', '„Tschüss.“ – und dann sofort ohne Gruß auflegen', '„Für so was habe ich wirklich keine Zeit, tschüss.“', '„Bitte rufen Sie mich nicht noch einmal an.“'], l: 0, e: 'Dank und ein guter Wunsch zum Schluss – das bleibt positiv in Erinnerung.' },
  { k: 'ende', q: 'Was passt NICHT zum Ende eines Smalltalks?', opts: ['„Und jetzt erzähle ich dir meine ganze Lebensgeschichte.“', '„Wir sehen uns dann gleich beim Meeting!“', '„War wirklich nett, mit dir zu plaudern.“', '„Bis morgen und schönen Feierabend!“'], l: 0, e: 'Smalltalk ist kurz – zwei bis fünf Minuten sind normal.' },
  // Kultur
  { k: 'kultur', q: 'Wie lange dauert Smalltalk am Arbeitsplatz normalerweise?', opts: ['ein paar Minuten', 'eine Stunde', 'den ganzen Vormittag', 'nur in der Mittagspause, nie sonst'], l: 0, e: 'Smalltalk ist kurz und leicht – er „wärmt“ die Beziehung auf, ersetzt aber nicht die Arbeit.' },
  { k: 'kultur', q: 'Warum ist Smalltalk im Beruf wichtig?', opts: ['Er schafft Vertrauen und eine gute Atmosphäre.', 'Er ersetzt lange und anstrengende Besprechungen.', 'Wer viel plaudert, bekommt mehr Gehalt.', 'Er ist in deutschen Firmen gesetzlich Pflicht.'], l: 0, e: 'Wer sich gut versteht, arbeitet auch besser zusammen.' },
  { k: 'kultur', q: 'Eine Kollegin hat Geburtstag. Was ist im Büro üblich?', opts: ['gratulieren – oft gibt es Kuchen von ihr', 'fragen, wie alt sie jetzt genau ist', 'nichts sagen, Geburtstage sind privat', 'ihr einen Umschlag mit Geld schenken'], l: 0, e: 'In vielen Teams bringt das Geburtstagskind selbst Kuchen mit.' },
  { k: 'kultur', q: 'Beim Smalltalk mit Kunden vor einem Meeting fragt man am besten …', opts: ['„Haben Sie gut hergefunden?“', '„Warum sind Sie so spät?“', '„Wie viel verdient Ihre Firma?“', '„Sind Sie verheiratet?“'], l: 0, e: 'Klassiker vor Terminen: Anreise, Wetter, Parkplatz, ein Getränk anbieten.' },
  { k: 'kultur', q: 'Was zeigt im Gespräch Interesse – ohne Worte?', opts: ['Blickkontakt und ein Lächeln', 'auf die Uhr schauen', 'die Arme verschränken', 'Nachrichten am Handy lesen'], l: 0, e: 'Körpersprache ist beim Smalltalk genauso wichtig wie die Worte.' }
];
